########################
## Volume Definitions ##
########################
# What volumes exist and how

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster-storage
  namespace: main
spec:
  storageClassName: cluster-pv
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate

###################
## Volume Claims ##
###################
# Who is assigned what volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: club-static-pvc
  namespace: main
spec:
  storageClassName: cluster-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
